/**
 * venueService.js
 * Mock venue data – replace with real API calls when backend is ready.
 * Each venue includes rich metadata for the Venue Details page.
 */

export const MOCK_VENUES = [
  {
    id:            'v1',
    name:          'The Globe Sports Bar',
    tagline:       'NYC\'s premier football viewing destination since 2008',
    address:       '14 W 33rd St, New York, NY 10001',
    city:          'New York',
    cityKey:       'new-york',
    province:      'New York',
    country:       'USA',
    lat:           40.7484,
    lng:           -73.9967,
    distance:      '0.3 mi',
    distanceNum:   0.3,
    capacity:      120,
    interestedCount: 47,
    attendingCount:  23,
    category:      'Sports Bar',
    badges:        ['Sports Bar', 'Near Transit', 'Popular'],
    rating:        4.6,
    ratingCount:   248,
    description:   'The Globe is a true football lover\'s haven in the heart of Midtown Manhattan. With 40+ HD screens, an authentic atmosphere, and a dedicated FIFA viewing section, this is where NYC fans come together for the beautiful game. Their signature match-day cocktails and loaded nachos are the stuff of legend.',
    hours:         { open: '11:00 AM', close: '2:00 AM' },
    highlights:    ['40+ HD screens', 'FIFA match-day menu', 'Private viewing booths', 'Craft beer wall'],
    accessibility: 'Wheelchair accessible via 33rd St entrance',
    transit:       'Penn Station – 2 min walk · 34th St B/D/F/M/N/Q/R – 3 min',
    parking:       'Paid parking on 34th St ($30/day)',
  },
  {
    id:            'v2',
    name:          'Kickoff Cantina',
    tagline:       'Where LA meets the world — match days done right',
    address:       '1234 Sunset Blvd, Los Angeles, CA 90026',
    city:          'Los Angeles',
    cityKey:       'los-angeles',
    province:      'California',
    country:       'USA',
    lat:           34.0780,
    lng:           -118.2740,
    distance:      '1.2 mi',
    distanceNum:   1.2,
    capacity:      200,
    interestedCount: 89,
    attendingCount:  54,
    category:      'Fan Zone',
    badges:        ['Fan Zone', 'Outdoor Patio', 'Family Friendly'],
    rating:        4.8,
    ratingCount:   512,
    description:   'Kickoff Cantina brings the energy of SoFi Stadium to the heart of Silver Lake. Known for its epic outdoor patio with two massive screens, a diverse food menu, and one of the best cocktail selections in LA, this is the ultimate California match-day experience. Expect electric crowds and unforgettable vibes.',
    hours:         { open: '10:00 AM', close: '1:00 AM' },
    highlights:    ['Outdoor patio 200+ capacity', 'Giant LED screens', 'Full Mexican & American menu', 'FIFA 2026 merch pop-up'],
    accessibility: 'Fully accessible. Dedicated parking spaces available.',
    transit:       'Metro Silver Line – Sunset/Alvarado Station – 5 min walk',
    parking:       'Free street parking on weekends',
  },
  {
    id:            'v3',
    name:          'Stadium View Brewery',
    tagline:       'Craft beers, Texas BBQ, and world-class football',
    address:       '456 Main St, Dallas, TX 75202',
    city:          'Dallas',
    cityKey:       'dallas',
    province:      'Texas',
    country:       'USA',
    lat:           32.7831,
    lng:           -96.8067,
    distance:      '0.8 mi',
    distanceNum:   0.8,
    capacity:      150,
    interestedCount: 63,
    attendingCount:  31,
    category:      'Brewery',
    badges:        ['Craft Brewery', 'Sports Bar', 'Local Fave'],
    rating:        4.5,
    ratingCount:   189,
    description:   'Stadium View Brewery is a Dallas institution blending Texas craft brewing culture with world-class football viewing. The exposed brick interiors, 20 rotating taps, and championship-sized screens make this the go-to spot for serious fans. The slow-smoked brisket platter during match days is legendary.',
    hours:         { open: '12:00 PM', close: '12:00 AM' },
    highlights:    ['20 rotating craft taps', 'Texas BBQ match-day menu', 'Rooftop viewing deck', 'Brewery tours available'],
    accessibility: 'Street-level accessible entrance. Elevator to rooftop.',
    transit:       'DART West End Station – 8 min walk',
    parking:       'Free parking lot behind venue (enter via Commerce St)',
  },
  {
    id:            'v4',
    name:          'The Corner Flag Café',
    tagline:       'Chicago\'s cozy neighbourhood football café',
    address:       '789 N Michigan Ave, Chicago, IL 60611',
    city:          'Chicago',
    cityKey:       'chicago',
    province:      'Illinois',
    country:       'USA',
    lat:           41.8962,
    lng:           -87.6235,
    distance:      '0.5 mi',
    distanceNum:   0.5,
    capacity:      80,
    interestedCount: 34,
    attendingCount:  17,
    category:      'Café',
    badges:        ['Café', 'Cosy Atmosphere', 'Near Transit'],
    rating:        4.4,
    ratingCount:   143,
    description:   'A beloved neighbourhood institution on the Magnificent Mile, The Corner Flag serves specialty coffees, artisan sandwiches, and an intimate match-day experience. With just 80 seats, every spot feels personal — you\'ll know your neighbours by full-time. Perfect for fans who prefer conversation over noise.',
    hours:         { open: '7:00 AM', close: '11:00 PM' },
    highlights:    ['Specialty coffee bar', 'Artisan match-day menu', 'Intimate atmosphere', 'Board game lounge'],
    accessibility: 'Step-free entrance from Michigan Ave. Accessible restrooms.',
    transit:       'Chicago Rd (Red Line) – 3 min walk',
    parking:       'Water Tower Place parking garage – 5 min walk ($25/day)',
  },
  {
    id:            'v5',
    name:          'Golazo Sports Lounge',
    tagline:       'Miami\'s hottest football destination — feel the heat',
    address:       '555 Biscayne Blvd, Miami, FL 33132',
    city:          'Miami',
    cityKey:       'miami',
    province:      'Florida',
    country:       'USA',
    lat:           25.7753,
    lng:           -80.1867,
    distance:      '2.1 mi',
    distanceNum:   2.1,
    capacity:      300,
    interestedCount: 128,
    attendingCount:  86,
    category:      'Sports Lounge',
    badges:        ['Premium Lounge', 'Oceanfront Views', 'Most Popular'],
    rating:        4.9,
    ratingCount:   731,
    description:   'Golazo is Miami\'s crown jewel for football fans. With a dramatic waterfront location, VIP sky boxes, and a rooftop bar overlooking Biscayne Bay, this is where Miami celebrities and hardcore fans watch together. The Latin-fusion menu and world-class cocktail program match the prestige of the venue.',
    hours:         { open: '11:00 AM', close: '3:00 AM' },
    highlights:    ['Biscayne Bay views', 'VIP sky boxes', 'Rooftop bar', 'Latin-fusion kitchen'],
    accessibility: 'Fully accessible. Valet service available.',
    transit:       'Metromover Bayfront Park – 3 min walk',
    parking:       'Valet parking $20 · Bayfront Park garage nearby',
  },
  {
    id:            'v6',
    name:          'Full Time Bar & Grill',
    tagline:       'Houston\'s most passionate football community',
    address:       '321 Westheimer Rd, Houston, TX 77006',
    city:          'Houston',
    cityKey:       'houston',
    province:      'Texas',
    country:       'USA',
    lat:           29.7396,
    lng:           -95.3972,
    distance:      '1.5 mi',
    distanceNum:   1.5,
    capacity:      100,
    interestedCount: 22,
    attendingCount:  11,
    category:      'Bar & Grill',
    badges:        ['Bar & Grill', 'Local Community', 'Family Friendly'],
    rating:        4.2,
    ratingCount:   98,
    description:   'Full Time is Houston\'s beloved neighbourhood football hub on Westheimer. Founded by former college players, it has the authentic grassroots energy that bigger venues can\'t replicate. Their all-day match-day brunches and dedicated family section make it welcoming for fans of all ages.',
    hours:         { open: '10:00 AM', close: '12:00 AM' },
    highlights:    ['Match-day brunch specials', 'Family section', 'Fantasy football leaderboards', 'Post-match analysis board'],
    accessibility: 'Accessible entrance via side ramp. Accessible parking available.',
    transit:       'METRO Local 82 bus – Westheimer/Montrose stop',
    parking:       'Free lot behind venue, enter from Yupon St',
  },
  {
    id:            'v7',
    name:          'The Golden Boot',
    tagline:       'Pacific Northwest football culture at its finest',
    address:       '88 Pike St, Seattle, WA 98101',
    city:          'Seattle',
    cityKey:       'seattle',
    province:      'Washington',
    country:       'USA',
    lat:           47.6085,
    lng:           -122.3409,
    distance:      '0.4 mi',
    distanceNum:   0.4,
    capacity:      90,
    interestedCount: 56,
    attendingCount:  28,
    category:      'Sports Pub',
    badges:        ['Sports Pub', 'Pike Place Adjacent', 'Near Transit'],
    rating:        4.7,
    ratingCount:   302,
    description:   'Steps from the iconic Pike Place Market, The Golden Boot has been Seattle\'s football heartbeat since 2012. The interior is a museum of global football memorabilia, and the draft list reads like a world tour of craft brewing. Pre-match walks through Pike Place are a Golden Boot tradition.',
    hours:         { open: '11:00 AM', close: '1:00 AM' },
    highlights:    ['Football memorabilia museum wall', '50+ global craft beers', 'Pre-match Pike Place tours', 'Legendary fish & chips'],
    accessibility: 'Accessible entrance from Pike St. Step-free throughout.',
    transit:       'Westlake Station – 6 min walk · Link Light Rail nearby',
    parking:       'Pike Place Market parking garage – 3 min walk ($15/2hrs)',
  },
  {
    id:            'v8',
    name:          'Copa Café & Bar',
    tagline:       'San Francisco\'s sophisticated match-day café',
    address:       '200 Market St, San Francisco, CA 94105',
    city:          'San Francisco',
    cityKey:       'san-francisco',
    province:      'California',
    country:       'USA',
    lat:           37.7943,
    lng:           -122.3952,
    distance:      '3.0 mi',
    distanceNum:   3.0,
    capacity:      60,
    interestedCount: 18,
    attendingCount:   9,
    category:      'Café',
    badges:        ['Specialty Coffee', 'Waterfront Adjacent', 'Quiet Atmosphere'],
    rating:        4.3,
    ratingCount:   87,
    description:   'Copa is San Francisco\'s most refined football café — a calm alternative to the usual match-day chaos. Overlooking the Embarcadero waterfront, with third-wave coffee, fresh pastries, and a curated selection of international beers, it\'s the spot where tech workers and football nerds unite.',
    hours:         { open: '8:00 AM', close: '10:00 PM' },
    highlights:    ['Third-wave specialty coffee', 'Embarcadero views', 'Pastry & cheese board menu', 'Silent screen option'],
    accessibility: 'Fully accessible. Step-free entrance and restrooms.',
    transit:       'Embarcadero BART/Muni – 4 min walk',
    parking:       'Embarcadero Center parking ($25/day)',
  },
  {
    id:            'v9',
    name:          'Ninety Minutes',
    tagline:       'Boston\'s legendary football destination since 2005',
    address:       '42 Boylston St, Boston, MA 02116',
    city:          'Boston',
    cityKey:       'boston',
    province:      'Massachusetts',
    country:       'USA',
    lat:           42.3555,
    lng:           -71.0666,
    distance:      '1.0 mi',
    distanceNum:   1.0,
    capacity:      175,
    interestedCount: 71,
    attendingCount:  42,
    category:      'Sports Bar',
    badges:        ['Sports Bar', 'Historic District', 'Live Entertainment'],
    rating:        4.6,
    ratingCount:   394,
    description:   'Ninety Minutes is a Boston institution on Boylston Street, minutes from the Boston Common. Home to the largest European football supporter section in New England, the atmosphere during big matches is electrifying. Their legendary post-match analysis nights have become a cultural fixture.',
    hours:         { open: '10:00 AM', close: '2:00 AM' },
    highlights:    ['New England\'s largest supporter sections', 'Live DJ on match nights', 'Boston Common proximity', 'Extensive New England craft beer list'],
    accessibility: 'Accessible via Boylston St ramp. Elevator to upper floor.',
    transit:       'Boylston (Green Line) – 2 min walk',
    parking:       'Boston Common Garage – 5 min walk ($25/day)',
  },
  {
    id:            'v10',
    name:          'Offside Bar & Kitchen',
    tagline:       'Portland\'s most welcoming football community',
    address:       '660 NW 23rd Ave, Portland, OR 97210',
    city:          'Portland',
    cityKey:       'portland',
    province:      'Oregon',
    country:       'USA',
    lat:           45.5272,
    lng:           -122.6996,
    distance:      '0.7 mi',
    distanceNum:   0.7,
    capacity:      110,
    interestedCount: 40,
    attendingCount:  21,
    category:      'Bar & Kitchen',
    badges:        ['Bar & Kitchen', 'Plant-Based Options', 'Dog Friendly'],
    rating:        4.5,
    ratingCount:   211,
    description:   'Offside is the beating heart of Portland\'s football community. In true Portland style, they champion sustainability, local sourcing, and inclusive culture. The plant-forward menu, rotating local taps, and dog-friendly patio have made Offside a beloved institution in the Pearl District.',
    hours:         { open: '12:00 PM', close: '1:00 AM' },
    highlights:    ['Dog-friendly patio', 'Extensive plant-based menu', 'Local & organic beer selection', 'Community football mural wall'],
    accessibility: 'Step-free entrance. Dog-friendly patio has accessible seating.',
    transit:       'TriMet Bus 77 – NW 23rd/Lovejoy stop',
    parking:       'Free street parking on NW 22nd Ave',
  },
  {
    id:            'v11',
    name:          'The Maple & Cleat',
    tagline:       'Toronto\'s ultimate FIFA 2026 fan headquarters',
    address:       '99 Queens Quay W, Toronto, ON M5J 2H2',
    city:          'Toronto',
    cityKey:       'toronto',
    province:      'Ontario',
    country:       'Canada',
    lat:           43.6410,
    lng:           -79.3820,
    distance:      '0.6 mi',
    distanceNum:   0.6,
    capacity:      250,
    interestedCount: 147,
    attendingCount:   93,
    category:      'Fan Zone',
    badges:        ['Official Fan Zone', 'Harbourfront', 'Most Popular'],
    rating:        4.9,
    ratingCount:   628,
    description:   'Steps from Lake Ontario on Queens Quay, The Maple & Cleat has established itself as Toronto\'s definitive World Cup experience. The multi-level venue features a stunning harbourfront terrace, live DJ sets, and the most diverse football-watching crowd in the city. With Canadian craft beers, poutine flights, and late-night parties, this is where Toronto comes alive for 2026.',
    hours:         { open: '10:00 AM', close: '3:00 AM' },
    highlights:    ['Harbourfront terrace with lake views', 'FIFA 2026 official fan zone status', 'Canadian craft beer selection', 'Poutine & Canadian cuisine menu', 'Live DJ sets'],
    accessibility: 'Fully accessible via Queens Quay PATH. Waterfront trail adjacent.',
    transit:       'Union Station – 10 min walk · 509/510 streetcar – Queens Quay stop',
    parking:       'Harbourfront Centre underground parking ($20/day)',
  },
  {
    id:            'v12',
    name:          'Kick-Off Brewing Co.',
    tagline:       'Vancouver\'s craft-beer home of world football',
    address:       '777 Beatty St, Vancouver, BC V6B 2M4',
    city:          'Vancouver',
    cityKey:       'vancouver',
    province:      'British Columbia',
    country:       'Canada',
    lat:           49.2782,
    lng:           -123.1109,
    distance:      '0.3 mi',
    distanceNum:   0.3,
    capacity:      180,
    interestedCount: 112,
    attendingCount:   67,
    category:      'Craft Brewery',
    badges:        ['Craft Brewery', 'Near BC Place', 'Mountain Views'],
    rating:        4.8,
    ratingCount:   445,
    description:   'Kick-Off Brewing Co. sits in the heart of Yaletown, a short walk from BC Place. Their 24 taps of house-brewed craft ales — including FIFA 2026 limited editions — draw massive crowds on match days. The exposed industrial interior, mountain-view patio, and legendary smash burgers make this the ultimate Vancouver football experience.',
    hours:         { open: '11:00 AM', close: '2:00 AM' },
    highlights:    ['24 house-brewed craft ales', 'FIFA 2026 limited edition beers', 'Mountain-view patio', 'Smash burger menu', 'Brewery tours between matches'],
    accessibility: 'Accessible entrance via Beatty St. Elevator to all floors.',
    transit:       'Stadium-Chinatown SkyTrain – 5 min walk · BC Place – 7 min walk',
    parking:       'Yaletown parking garage on Hamilton St ($15/day)',
  },
  {
    id:            'v13',
    name:          'La Cantina Azteca',
    tagline:       'Mexico City football culture — pure and electric',
    address:       'Insurgentes Sur 3646, Tlalpan, CDMX 14000',
    city:          'Mexico City',
    cityKey:       'mexico-city',
    province:      'CDMX',
    country:       'Mexico',
    lat:           19.3680,
    lng:           -99.1858,
    distance:      '1.0 km',
    distanceNum:   1.0,
    capacity:      220,
    interestedCount: 195,
    attendingCount:  134,
    category:      'Sports Bar',
    badges:        ['Sports Bar', 'Near Estadio Azteca', 'Iconic Venue'],
    rating:        4.9,
    ratingCount:   982,
    description:   'La Cantina Azteca is a Mexico City legend. Operating since 1982, this football shrine near the Estadio Azteca has hosted celebrations for every major Mexican triumph. The walls are covered in signed jerseys, historic photos, and scarves from across the globe. Pre-match mezcal flights and post-match mariachi nights are unmissable.',
    hours:         { open: '9:00 AM', close: '2:00 AM' },
    highlights:    ['Mexico City football history museum wall', 'Pre-match mezcal & tequila flights', 'Post-match mariachi', 'Traditional Mexican kitchen', 'Near Azteca – 10 min walk'],
    accessibility: 'Accessible entrance. Taxi/rideshare recommended.',
    transit:       'Metro Estadio Azteca (Line 2) – 12 min walk',
    parking:       'On-site paid parking available ($50 MXN/day)',
  },
];

export function getVenues() {
  return Promise.resolve([...MOCK_VENUES]);
}

export function getVenueById(id) {
  return Promise.resolve(MOCK_VENUES.find((v) => v.id === id) ?? null);
}
